{% set data = load_setup_py_data(setup_file='../setup.cfg', from_recipe_dir=True) %}
{% set version = load_setup_py_data(setup_file='../commlib/__init__.py', from_recipe_dir=True) %}

package:
  name: commlib-py
  version: {{ version['__version__'] }}

source:
  path: .

build:
  noarch: python
  script: {{ PYTHON }} setup.py install
  number: 0

requirements:
  build:
    - python
    - poetry-core
  run:
    - python >=3.8.0
    - pika >=1.3.1
    - paho-mqtt >=1.6.1
    - hiredis >=2.1.1
    - ujson >=5.7.0
    - pydantic >=1.10.4

test:
  imports:
    - commlib
  requires:
    - coverage
  source_files:
    - tests
    - Makefile
  commands:
    - make test

about:
  home: {{ data['url'] }}
  summary: {{ data['description'] }}
  license: {{ data['license'] }}
  license_file:
    - LICENSE.txt
    - LICENSE

extra:
  recipe-maintainers:
    - memento
