{% set name = "commlib-py" %}
{% set data = load_setup_py_data() %}

package:
  name: {{ name|lower }}
  version: {{ data['version'] }}

source:
  path: .

build:
  noarch: python
  script: {{ PYTHON }} setup.py install
  number: 0

requirements:
  build:
    - python
    - poetry-core
  run:
    - python >=3.8.0
    - pika >=1.3.1
    - paho-mqtt >=1.6.1
    - hiredis >=2.1.1
    - ujson >=5.7.0
    - pydantic >=1.10.4

test:
  imports:
    - commlib
  requires:
    - coverage
  source_files:
    - tests
    - Makefile
  commands:
    - make test

about:
  home: https://github.com/robotics-4-all/commlib-py
  summary: "Internal  DSL for communication and messaging in CPS"
  license: MIT
  license_file:
    - LICENSE.txt
    - LICENSE

extra:
  recipe-maintainers:
    - memento
