name: publish_conda

on:
  release:
    types: [published]
    
jobs:
  publish:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Set Environment Variables
      run: |
        sed "/#/d" ./.github/variables/anaconda_variables.env >> "$GITHUB_ENV"
        echo "" >>  "$GITHUB_ENV"
        echo "RELEASE_VERSION=$(awk -F'\"' '/__version__/ {print $2}' commlib/__init__.py)" >> "$GITHUB_ENV"
      shell: bash

    - name: Install Miniconda
      uses: conda-incubator/setup-miniconda@v2
      with:
        miniconda-version: "latest"
        python-version: 3.11
        auto-update-conda: true
        auto-activate-base: true
        use-only-tar-bz2: true

    - name: Verify conda environment
      run: |
        conda activate base
        conda info | grep "user-agent"

    - name: Install Anaconda Client & Conda build - Activate base!
      run: |
        conda install -y anaconda-client conda-build

    - name: Build conda package
      run: |
        conda build -c conda-forge --output-folder ${{ env.CONDA_BUILD_DIR }} .conda
    
    - name: Upload package
      run: |
        find ${{ env.CONDA_BUILD_DIR }} -name *.tar.bz2 | while read file
        do
            anaconda -t ${{ secrets.ANACONDA_TOKEN }} -u ${{ env.ANACONDA_CHANNEL }} upload $file
        done
    
    - name: Cleanup
      run: |
        rm -rf ${{ env.CONDA_BUILD_DIR }}
